use_frameworks!


source '/Users/Tian/.cocoapods/repos/TZYSpecs'
source 'https://github.com/CocoaPods/Specs.git'

target 'JingDataPodResourceLoader_Example' do
  pod 'JingDataPodResourceLoader', :path => '../'

  target 'JingDataPodResourceLoader_Tests' do
    inherit! :search_paths

    
  end
end
